# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "nibabel" %}
{% set version = "2.3.2" %}
{% set sha256 = "eaf571b7463d41cfc4d60b1f52cd18b8ad981a3c936c4fe6779eaf26f4086ce2" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 1000
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - numpy
    - h5py
    - pydicom
  run:
    - python
    - numpy
    - scipy
    - h5py
    - pydicom
    - bz2file  # [py27]

test:
  imports:
    - nibabel

about:
  home: https://nipy.org/nibabel
  license: MIT
  license_file: COPYING
  summary: Python package to access a cacophony of neuro-imaging file formats

extra:
  recipe-maintainers:
    - arokem
    - grlee77
    - effigies
