# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "nibabel" %}
{% set version = "5.3.0" %}
{% set sha256 = "68a9b786e2d2dbf5b9f02dcf73b2400d54e20ffb8521591ac0e504ca283664a6" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nib-conform  = nibabel.cmdline.conform:main
    - nib-convert  = nibabel.cmdline.convert:main
    - nib-dicomfs  = nibabel.cmdline.dicomfs:main
    - nib-diff     = nibabel.cmdline.diff:main
    - nib-ls       = nibabel.cmdline.ls:main
    - nib-nifti-dx = nibabel.cmdline.nifti_dx:main
    - nib-roi      = nibabel.cmdline.roi:main
    - nib-stats    = nibabel.cmdline.stats:main
    - nib-tck2trk  = nibabel.cmdline.tck2trk:main
    - nib-trk2tck  = nibabel.cmdline.trk2tck:main
    - parrec2nii   = nibabel.cmdline.parrec2nii:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.9
    - pip
    - hatchling
    - hatch-vcs
    - setuptools_scm
  run:
    - python >=3.9
    - packaging >=20
    - numpy >=1.22
    - importlib_resources >=5.12
    - typing_extensions >=4.6

test:
  requires:
    - pytest
    - pytest-doctestplus
    - pytest-httpserver
    - pytest-xdist
    - scipy
    - pillow
    - h5py
    - indexed_gzip
    - matplotlib
    - pydicom
    - pyzstd
  imports:
    - nibabel
  commands:
    - nib-conform --help
    - nib-convert --help
    - nib-dicomfs --help
    - nib-diff --help
    - nib-ls --help
    - nib-nifti-dx --help
    - nib-roi --help
    - nib-stats --help
    - nib-tck2trk --help
    - nib-trk2tck --help
    - parrec2nii --help
    - pytest --doctest-modules --doctest-plus --pyargs nibabel -n auto


about:
  home: https://nipy.org/nibabel
  license: MIT
  license_file: COPYING
  summary: Python package to access a cacophony of neuro-imaging file formats

extra:
  recipe-maintainers:
    - arokem
    - grlee77
    - effigies
