# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "nibabel" %}
{% set version = "2.3.1" %}
{% set sha256 = "5d3d59dbd29539713fb061cd4afb3b675b692f89eb76b6b385098e39196a066f" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - numpy
    - h5py
    - pydicom
  run:
    - python
    - numpy
    - scipy
    - h5py
    - pydicom

test:
  imports:
    - nibabel

about:
  home: https://nipy.org/nibabel
  license: MIT
  license_file: COPYING
  summary: Python package to access a cacophony of neuro-imaging file formats

extra:
  recipe-maintainers:
    - arokem
    - grlee77
    - effigies
