# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "nibabel" %}
{% set version = "5.0.0" %}
{% set sha256 = "763f075bca72b17fbde792d028ee7624de0d70fb1fab442dae810570badf2595" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - parrec2nii   = nibabel.cmdline.parrec2nii:main
    - nib-ls       = nibabel.cmdline.ls:main
    - nib-dicomfs  = nibabel.cmdline.dicomfs:main
    - nib-nifti-dx = nibabel.cmdline.nifti_dx:main
    - nib-tck2trk  = nibabel.cmdline.tck2trk:main
    - nib-trk2tck  = nibabel.cmdline.trk2tck:main
    - nib-diff     = nibabel.cmdline.diff:main
    - nib-conform  = nibabel.cmdline.conform:main
    - nib-roi      = nibabel.cmdline.roi:main
    - nib-stats    = nibabel.cmdline.stats:main

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
    - setuptools_scm
  run:
    - python >=3.8
    - packaging >=17
    - numpy >=1.19
    - setuptools

test:
  imports:
    - nibabel
  commands:
    - parrec2nii --help
    - nib-ls --help
    - nib-dicomfs --help
    - nib-nifti-dx --help
    - nib-tck2trk --help
    - nib-trk2tck --help
    - nib-diff --help
    - nib-conform --help
    - nib-roi --help
    - nib-stats --help


about:
  home: https://nipy.org/nibabel
  license: MIT
  license_file: COPYING
  summary: Python package to access a cacophony of neuro-imaging file formats

extra:
  recipe-maintainers:
    - arokem
    - grlee77
    - effigies
