# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "nibabel" %}
{% set version = "2.5.1" %}
{% set sha256 = "47b445abee203a9ab4068d826588f926352ea55f20a894178ad5b56215a22fd8" %}

# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 1
    script: "{{ PYTHON }} -m pip install . -vv"
    entry_points:
      - parrec2nii   = nibabel.cmdline.parrec2nii:main
      - nib-ls       = nibabel.cmdline.ls:main
      - nib-dicomfs  = nibabel.cmdline.dicomfs:main
      - nib-nifti-dx = nibabel.cmdline.nifti_dx:main
      - nib-tck2trk  = nibabel.cmdline.tck2trk:main
      - nib-trk2tck  = nibabel.cmdline.trk2tck:main
      - nib-diff     = nibabel.cmdline.diff:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - h5py
    - pydicom
    - six
    - bz2file  # [py27]

test:
  imports:
    - nibabel
  commands:
    - parrec2nii --help
    - nib-ls --help
    - nib-dicomfs --help
    - nib-nifti-dx --help
    - nib-tck2trk --help
    - nib-trk2tck --help
    - nib-diff --help


about:
  home: https://nipy.org/nibabel
  license: MIT
  license_file: COPYING
  summary: Python package to access a cacophony of neuro-imaging file formats

extra:
  recipe-maintainers:
    - arokem
    - grlee77
    - effigies
