travis:
  secure:
    BINSTAR_TOKEN: Tr0heM13Db+fnkjzF+Rw4cok6ah+sZDv5FFUuQuhcP+enjJR/AO1qeAfnUrBIoZLK9rA2F7/jnrExIUMZa1XzJExKuG3Ot55TYvYI+aRIqeMztbj8YfT2KR086D6WtZ4sCfrtyp/B4pFvRcGB6siyYvZ2BSihy+NYeW3sEiW8CPy94xSvAY8BIrUVrIKH4odtKjio7DirjS95uhxWyDzYGH5u1p0Dfmz8Q7NYYvRdba+FNd0lx82VSuolShu7H4nADC23Xfo3pH48x2AD80PTUCj1v8+RnLViQoWlKbjp8BhYb80Gx56OCjW5f7GraGSIrBrjoJ4EhT5DzIKNERwgyxrW2KSHaV85Eb3R70ag2kkktyCz3t3gdcoCyC4NsVcAWJbWdvJ9ycCRuGacx2ehdsS/yXLNKB+NFDia5g9k7XeKELILcdtg56mgas02OetKdIunTTj+/P7Na+nVQEXpQawPFQ0Dg8P6RaolRUbJOKDrVyPH2I9SiRtMW5IagmIs0biaOBj2cFgW1+GhyD2194v9beeSk06euqc77YJvbw9dTLpMNgcbWbm306ZynZqkVhIFh13j8qE+lfDI3FUYTymFX3dv1o5JhZjtZOrj49CJs/+elwC5kK74FavSDKNb/6dFedEqD2rMM/aZdFN6a7zFuN26M/s/PFOin9bfWE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
